name: Deploy on GitHub Pages
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10
      # - run: pip install mkdocs-material 
      - run: pip --trusted-host pypi.org --trusted-host files.pythonhosted.org install pymdownx mkdocs-material mkdocs-material-extensions mkdocs-macros-plugin
      - run: mkdocs gh-deploy --force
